### ISSUE TITLE
Update the Readme

### ISSUE THREAD

**Issue by raultron** [slinshady89/dynamic_distortion_calibrator#1]
It would be nice to have on the readme information about the current status of the project:

- Functionality that is available right now
- Future plans
- Works in progress

Additionally the Readme in its current state does not describe exactly the set of steps to follow in order to install and run the package.

Some examples: 
- [https://github.com/kylemcdonald/FaceTracker](https://github.com/kylemcdonald/FaceTracker)
- [https://github.com/raultron/tud_coop_uv](https://github.com/raultron/tud_coop_uv)
- [https://github.com/raultron/ar_nav](https://github.com/raultron/ar_nav)

**Comment by slinshady89** [comment]
I already checked your projects for input and saw the better Readme's. Maybe I will ask someone of the group to update ours.
