### ISSUE TITLE
Collaboration.

### ISSUE THREAD

**Issue by raultron** [slinshady89/dynamic_distortion_calibrator#2]
Are you the only member of the team working on the code?, I can only see your commits... I will like to see the other members working. You can give them permissions to work directly in this repository or they can work in a fork of this repo in their own account and then make Pull Request with the additions.

Tutorial for team collaboration: [https://code.tutsplus.com/articles/team-collaboration-with-github--net-29876](https://code.tutsplus.com/articles/team-collaboration-with-github--net-29876)

**Comment by slinshady89** [comment]
The others have the permission. But only Vivica was able to setup Visual Studio with openframeworks and the project, and she added the first form of the spiral functionality. The project now compiles at the computer of the other two too.
