### ISSUE TITLE
progress class findPixelSize

### ISSUE THREAD

**Issue by ghost** [slinshady89/dynamic_distortion_calibrator#4]
Text largely copy-pasted from e-mail for better discussion:

I've overhauled our PixelSizeDetector class. It should largely work now. 
The overhaul includes:
- creating a state machine in draw() function instead of trying to figure out the internal timing of openframeworks with update() and draw() as Raul suggested to us today

- extracting some drawing stuff to other functions
- including a debug draw that we can easily turn off using line 65
- debug draw: first image: difference camera input and background, second image: camera input, third image: background

- using a mouse click in order to begin everything and then a second one to capture the background

- minimal instructions on what to do

What we still need to do there is:
- line   99: decide on the amount of times we want to draw the same screen, in order to make sure it's actually there

- line 129: decide/test/verify what value works for the minimal maxBrightness we need to detect to have found a white square. Maybe we need to automate this, if it varies too much on different screens.

- line 140: decide how often we want to have encountered the same pixelSize before we accept it. This should ensure, that we avoid deciding too quickly on a pixelSize, if there's some disturbance (short flash of light or something like that)

- maybe automate background capture as in findCameraArea class? Setup for camera should remain though. Ideas?

Everything else should work, but maybe I'm also overlooking something, so feel free to add! :)
I get a consistent pixelSize of 1 with my external webcam.

**Comment by slinshady89** [comment]
- I think the amount of 10 is okay as for it's only checked once 

- the brightness of 150 could be set lower if there is a declaration for the user to ensure that their are no reflections of other lightsources 

- totally okay with your amount since it wont need that much time and in another test I had issues if I wait less than 4 times!

- Sorry I don't get the point. Please tell me directly what you mean ;)

**Comment by ghost** [comment]
- We wait for 10 frames everytime the state machine switches into the drawing state (_state == 0). A lower amount would speed everything up a little, but the results might get less stable.

- Okay, so maybe we could add a line to the initial "instructions". "Normal" ambient light gets filtered out through the background subtraction, but direct light sources should be avoided. (Makes sense, a direct light source sets the brightness values to 255 and that's the cut off in terms of brightness. Even if we draw on a white pixel then, it's still 255 and gets reduces to 0 from background subtraction)

- Great, thank you for checking that out! :) What sorts of problem did you encounter, if you didn't check the pixel size at least 4 times?

- In PixelSizeDetector, we capture the background, when the user clicks for the second time (first click kicks off the running of the program in order to ensure, that the "instructions" were read). In CameraAreaDetector, this works automatically. In state -1 (set up state, lines 90 - 102) we wait until the screen has been drawn 50 times (line 96) and then grab whatever we see at that point as the background. I thought, that maybe we could reuse that in PixelSizeDetector and automate the backgroudn capturing, but it just occured to me, that it wouldn't work: We also need to leave room for the user to adjust the camera at the beginning of the program, so that it only sees the screen. And that can only be reliably done, if the user decides, when they're done. So, if they're done with adjusting their camera, they click, and then we can also just grab the background at that point.

- Additional point, as a result from the one above: We need to leave some of our debugDraw in the final program. The user needs to be able to see, what the camera sees, else they can't adjust it. We can remove it once the actual detection stuff kicks off, but it might be nice to have some visualization for the user.

**Comment by ghost** [comment]
Works, no more issues here ;)
