### ISSUE TITLE
progress class findCameraArea

### ISSUE THREAD

**Issue by ghost** [slinshady89/dynamic_distortion_calibrator#5]
Hi all,

I've overhauled the class. It largely works, but there's still a bunch of stuff to do.

What I've done:

- state machine in draw() function instead of using update() function

- automated background capturing in "setup" state of draw() (_state == -1)

- some debug displaying, like in findPixelSize. Addtionally there: red circle only drawn if white dot was seen. Green overlay for seen pixels (it's not stable, neither the overlay nor the setting of the color in line 202)

- simple code for pixel movement

What's definitly to be done there:

- make sure automatic background capturing works. Is implemented by counting the draws in setup state

- better movement code, maybe integrate the spiral again?

- look at brightness values for white and green overlay. Is there a better way to figure out the brightness values than hardcode them? Is there a way to make the minimal brightness value for white global?

- keep green overlay visible for user information

Feel free to add stuff, change things etc.

Cheers!

**Comment by slinshady89** [comment]
1. The Backround-capturing works fine now
2. Implemented the spiral again and a good start position for spiral by a function that finds the average mid of the camera frame
3. checked a second function ( lightness() ) to maybe solve the brightness problem. Seen brightness variates between ~100-200 for the seen white pixels in lightness less but still the same variance



**What I've done today ( Thanks for some help to Vivica! )**

- added a new function that draws one after another interception points of a chessboard grid on the screen and added cumulatively the positions of the recognized points. After that I devide this by the amount of detected points so I get a relatively mean point that should be in the mid of the camera frame. There the spiral for further tasks starts. 

- also added the spiral function we once had for faster movement in our camera frame

- made some timing tests how fast we could run the code how long do we need to wait in the state space machine

**Things that need to be checked**

1.  I added a function `detectBordersOfFrame()` that should find the outter border of the camera frame

**Comment by ghost** [comment]
1. Thanks for testing that. It would be great, if everyone else could check out, whether that works for them, too. I'm a bit worried, that it might not work out on every computer.

2. The way you calculate the initial position is great! It yields a pretty good result, with relatively easy code and a pretty quick run. Maybe we can cease drawing the rectangles, after they've run out of the image? Maybe something like, remember the most right x-value for which the rectangle gets detected by the camera. If it's not detected, when it's at that position, cease? Do you think something like that could work?

3. Cool! Did it work better/similiarly/worse than what we currently have? Should we maybe find the value for white by having the user click on certain areas at the beginning of the program (i.e. at the beginning of PixelSizeDetector, where they also adjust the camera and set the background)?

4. I'm curious, what were the results of your timing tests?

5. I'm sorry, I can't find the function? What class is it in and at roughly which line? ^^'

**Comment by slinshady89** [comment]
5. Maybe I should push it so you could see it ;)
2. Thanks ;) yeah to go back if we stop detecting pixels is a good idea I will try to implement this.
3. No the other function is not better but even worse I think. 
4. I could adjustments are very slight and less worth mentioning

**Comment by ghost** [comment]
I think we're largely done here, then, as this class is only supposed to find the area of the seen screen.
I think the accurate middle point detection and thus offset calculation should be done in the DynamicDistortionCalibrator class.

So the only thing left here, is to stop the rough middle point detection, once the squares are out of range for the image.

We should try to make the threshold for white pixels a global variable, so that we only have to set it once and not multiple times. It should be visible for all classes, I think.

**Comment by slinshady89** [comment]
is deprecated. 
Will be replaced by cameraBorderDetector with another concept.
